[package]
name = "dyn_type"
version = "0.1.0"
edition = "2018"

[dependencies]
dyn-clonable = "0.9.0"
itertools = "0.9"
lazy_static = "1.3.0"
pegasus_common = { path = "../../engine/pegasus/common" }
