apiVersion: v1
kind: Pod
metadata:
  name: unique_pod_name
  labels:
    graph: unique_pod_name
spec:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: kubernetes.io/hostname
  #           operator: In
  #           values:
  #           - k8s_node_host
  containers:
  - image: gremlin_image
    resources:
      requests:
        cpu: requests_cpu
        memory: requests_mem
      limits:
        cpu: limits_cpu
        memory: limits_mem
    name: gremlin-container
    imagePullPolicy: IfNotPresent
    args: ["/home/maxgraph/bin/giectl.sh", "start_frontend", "unique_object_id", "schema_path", "2181"]
    env:
    - name: OBJECT_ID
      value: 'unique_object_id'
    volumeMounts:
    - mountPath: /home/maxgraph/config
      name: config-volume
  - image: coordinator_image
    resources:
      requests:
        cpu: requests_cpu
        memory: requests_mem
      limits:
        cpu: limits_cpu
        memory: limits_mem
    name: coordinator-container
    imagePullPolicy: IfNotPresent
    args: ["/home/maxgraph/bin/giectl.sh", "start_coordinator", "unique_object_id", "2181"]
    env:
    - name: OBJECT_ID
      value: 'unique_object_id'
    volumeMounts:
    - mountPath: /home/maxgraph/config
      name: config-volume
  volumes:
  - name: config-volume
    configMap:
      name: unique_config_name
