log_level: INFO # default INFO
compute_engine:
  thread_num_per_worker: 1  # the number of shared workers, default 1
compiler:
  planner:
    is_on: true
    opt: RBO
    rules:
      - FilterIntoJoinRule
      - FilterMatchRule
      - NotMatchToAntiJoinRule
  query_timeout: 20000 # query timeout in milliseconds, default 2000