apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphscope-store-service.ingestor.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels: {{- include "graphscope-store-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestor
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: port
      port: {{ .Values.ingestor.service.port }}
      targetPort: port

  selector: {{- include "graphscope-store-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingestor
