addr: null
mode: eager
cluster_type: k8s
k8s_namespace: null
k8s_image_registry: registry.cn-hongkong.aliyuncs.com
k8s_image_repository: graphscope
k8s_image_pull_policy: IfNotPresent
k8s_image_pull_secrets: []
k8s_coordinator_cpu: 0.5
k8s_coordinator_mem: 512Mi
etcd_addrs: null
etcd_listening_client_port: 2379
etcd_listening_peer_port: 2380
k8s_vineyard_image: vineyardcloudnative/vineyardd:latest
k8s_vineyard_deployment: null
k8s_vineyard_cpu: 0.5
k8s_vineyard_mem: 512Mi
vineyard_shared_mem: null
k8s_engine_cpu: 0.2
k8s_engine_mem: 1Gi
mars_worker_cpu: 0.2
mars_worker_mem: 4Mi
mars_scheduler_cpu: 0.2
mars_scheduler_mem: 2Mi
k8s_coordinator_pod_node_selector: null
k8s_engine_pod_node_selector: null
enabled_engines: analytical,interactive,learning
with_mars: false
with_dataset: false
k8s_volumes: {}
k8s_service_type: NodePort
preemptive: true
k8s_deploy_mode: eager
k8s_waiting_for_delete: false
num_workers: 2
show_log: false
log_level: INFO
timeout_seconds: 600
dangling_timeout_seconds: 600
dataset_download_retries: 3