newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template! And a maintainer will get back to you shortly!

  Please feel free to contact us on [DingTalk](https://qr.dingtalk.com/action/joingroup?code=v1,k1,FuRFUjfpVjgGjwM71FP40Wqylw0VfdvQHggo8dhlZdI=&_dt_no_comment=1&origin=11?), WeChat account(graphscope) or [Slack](http://slack.graphscope.io/). We are happy to answer your questions responsively.

newPRWelcomeComment: >
  Thanks for submitting your first pull request! You are awesome! 🤗

  Please make sure you have signed the [CLA](https://cla-assistant.io/alibaba/GraphScope), as this is a mandatory check before a PR being merged.

  Welcome to the GraphScope community! 🎉 You can meet the community on [DingTalk](https://h5.dingtalk.com/circle/healthCheckin.html?dtaction=os&corpId=dingb4b76e0fa9ccd8d516fd0f0acdf19f55&68e71190=0fe34ec0&cbdbhh=qwertyuiop) or [Slack](http://slack.graphscope.io/).
