[package]
name = "pegasus_server"
version = "0.1.0"
authors = ["chenqiang.mcq <chenqiang.mcq@alibaba-inc.com>"]
edition = "2018"

[dependencies]
pegasus_common = { path = "../common" }
pegasus_network = { path = "../network"}
pegasus_memory = { path = "../memory"}
pegasus = { path = "../pegasus" }
log = "0.4"
crossbeam-utils = "0.8.14"
#crossbeam-channel = "0.5.6"
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.24", features = ["macros", "sync", "rt-multi-thread"] }
tokio-stream = "0.1.11"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
hyper = "0.14"
futures = { version = "0.3", default-features = false }
libloading = "0.7"


[dev-dependencies]
#libloading = "0.7"
structopt = "0.3"

[build-dependencies]
tonic-build = "0.8"

[features]
default = []
# set to generate code in place(generated codes are in current codebase);
gcip = []

