[package]
name = "pegasus"
version = "0.1.0"
authors = ["chenqiang.mcq <chenqiang.mcq@alibaba-inc.com>"]
edition = "2018"

[dependencies]
pegasus_common = { path = "../common" }
pegasus_memory = { path = "../memory" }
pegasus_network = { path = "../network" }
pegasus_executor = { path = "../executor" }
crossbeam-channel = "0.3.6"
crossbeam-queue = "0.1"
crossbeam-utils = "0.6"
log = "0.4"
smallvec = "0.6.9"
lazy_static = "1.3.0"
backtrace = "0.3.45"
bitflags = "1.2.1"
hibitset = "0.6.3"
enum_dispatch = "0.3"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }

[features]
default = []
mem = ["pegasus_memory/mem"]

[dev-dependencies]
time = "0.1"
env_logger = { version = "0.6" }
structopt = "0.2"
rand = "0.8.3"
