version: '3' # version of docker-compose
services:
  engine:
    image: "registry.cn-hongkong.aliyuncs.com/graphscope/hiactor-server:v0.0.1"
    ports:
     - "10000:10000"
    container_name: hqps-server
#    command : ["./hiactor-server", "-c", "config.yaml"] # command to start hqps_server
    volumes : 
      - /home/zhanglei/gie-db:/root/db_config # mount db directory
  compiler:
    image: "registry.cn-hongkong.aliyuncs.com/graphscope/hiactor-server:v0.0.1"
    ports: 
    - "8182:8182"
    container_name: hqps-compiler
#    command : ["./hiactor-compiler", "-c", "config.yaml"] # command to start hqps_compiler
    depends_on:
      - engine 