{{- if not .Values.distributedDeployment }}
{{- include "util.statefulsets" (list . "store.statefulset") -}}
{{- end -}}

{{- define "store.statefulset" -}}
metadata:
  name: {{ include "graphscope-store.store.fullname" . }}
  labels:
    app.kubernetes.io/component: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: store
  serviceName: {{ printf "%s-store-headless" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  template:
    metadata:
      labels:
        {{- include "common.tplvalues.render" (dict "value" .Values.store.podLabels "context" $) | nindent 8 }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.store.podAnnotations "context" $) | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.store.hostNetwork }}
      hostIPC: {{ .Values.store.hostIPC }}
      {{- if .Values.store.schedulerName }}
      schedulerName: {{ .Values.store.schedulerName | quote }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ include "graphscope-store.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
          {{- if .Values.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
          {{- end }}
          name: default
          ports:
            - name: grpc
              containerPort: {{ .Values.frontend.service.servicePort }}
            - name: gremlin
              containerPort: {{ .Values.frontend.service.gremlinPort }}
            - name: inner-rpc
              containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: ROLE
              value: ""
            - name: KAFKA_SERVERS
              value: {{ include "graphscope-store.kafka.brokerlist" . }}
            - name: ZK_CONNECT
              value: {{ printf "%s-headless" (include "graphscope-store.zookeeper.fullname" .) | quote }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.livenessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: gremlin
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.readinessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: gremlin
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: gremlin
          {{- end }}
          {{- if .Values.store.resources }}
          resources: {{- toYaml .Values.store.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/groot/groot.config.tpl
              subPath: groot.config
            - name: config
              mountPath: /etc/groot/setup.sh
              subPath: setup.sh
            - name: data
              mountPath: {{ .Values.storeDataPath }}
      volumes:
        - name: config
          configMap:
            name: {{ include "graphscope-store.configmapName" . }}
            defaultMode: 0755
  {{- if and .Values.store.persistence.enabled .Values.store.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.store.persistence.existingClaim . }}
  {{- else if not .Values.store.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else if and .Values.store.persistence.enabled (not .Values.store.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.store.persistence.size | quote }}
        {{ include "graphscope-store.storageClass" . | nindent 8 }}
{{- end -}}
{{- end -}}