#!/bin/bash

mkdir -p ~/.config/git/hooks/
git config --global core.hooksPath ~/.config/git/hooks/
touch ~/.config/git/hooks/prepare-commit-msg
chmod +x ~/.config/git/hooks/prepare-commit-msg

cat > ~/.config/git/hooks/prepare-commit-msg << EOF
#!/bin/bash
COMMIT_MSG_FILE=\$1
echo "" >> "\$COMMIT_MSG_FILE"
username=\$(git config --get user.name)
echo "Commited by: \$username from Dev container" >> "\$COMMIT_MSG_FILE"
EOF
