apiVersion: v1
kind: Service
metadata:
  name: coordinator-service-{{ include "graphscope.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- include "graphscope.service.annotations" . | nindent 2 }}
  labels:
    {{- include "graphscope.coordinator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.coordinator.service.type }}
  selector:
    {{- include "graphscope.coordinator.labels" . | nindent 4 }}
  ports:
    - port: 59001
      targetPort: 59001
      protocol: TCP
      name: rpc
    {{- if .Values.withJupyter }}
    - port: 8888
      nodePort: {{ .Values.jupyter.port }}
      name: http
    {{- end }}
