[package]
name = "pegasus_memory"
version = "0.1.0"
authors = ["chenqiang.mcq <chenqiang.mcq@alibaba-inc.com>"]
edition = "2018"

[features]
default = []
mem = []

[dependencies]
#log = "0.4"
crossbeam-utils = "0.7.0"
lazy_static = "1.3.0"