apiVersion: v1
kind: Pod
metadata:
  name: unique_pod_name 
  labels:
    graph: unique_pod_name
spec:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: kubernetes.io/hostname
  #           operator: In
  #           values:
  #           - k8s_node_host 
  containers:
  - image: gremlin_image
    resources:
      requests:
        cpu: gremlin_server_cpu
        memory: gremlin_server_mem
      limits:
        cpu: gremlin_server_cpu
        memory: gremlin_server_mem
    name: gremlin-container
    imagePullPolicy: IfNotPresent
    args: ["/home/maxgraph/frontend-entrypoint.sh"]
    env:
    - name: object_id
      value: 'unique_object_id'
    volumeMounts:
    - mountPath: /home/maxgraph/config
      name: config-volume
  - image: coordinator_image
    resources:
      requests:
        cpu: gremlin_server_cpu
        memory: gremlin_server_mem
      limits:
        cpu: gremlin_server_cpu
        memory: gremlin_server_mem
    name: coordinator-container
    imagePullPolicy: IfNotPresent
    args: ["/home/maxgraph/coordinator-entrypoint.sh"]
    env:
    - name: object_id
      value: 'unique_object_id'
    volumeMounts:
    - mountPath: /home/maxgraph/config
      name: config-volume
  volumes:
  - name: config-volume
    configMap:
      name: unique_config_name
