[package]
name = "pegasus"
version = "0.0.1"
authors = ["chenqiang.mcq <chenqiang.mcq@alibaba-inc.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.4.4"
crossbeam-queue = "0.1"
crossbeam-utils = "0.6"
env_logger = { version = "0.6" }
log = "0.4"
structopt = "0.2"
rand = "0.6"
abomonation = "0.7"
abomonation_derive = "0.3"
byteorder = "1.3.0"
time = "0.1"
smallvec = "0.6.14"
bincode = "1.0.1"
serde = "1.0.72"
serde_derive = "1.0.72"
lazy_static = "1.3.0"
tokio-io = "0.1"
tokio = "0.1.22"
futures = "0.1.25"
[target.'cfg(target_os = "linux")'.dependencies]
psutil = "=1.1.1"


[features]
default = []

padding = []
mem = []

#[dev-dependencies]
#tempdir = "0.3.7"
#timely = "0.10.0"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
