/*
 * GraphScope Interactive API v0.0.3
 * This is the definition of GraphScope Interactive API, including   - AdminService API   - Vertex/Edge API   - QueryService   AdminService API (with tag AdminService) defines the API for GraphManagement, ProcedureManagement and Service Management.  Vertex/Edge API (with tag GraphService) defines the API for Vertex/Edge management, including creation/updating/delete/retrive.  QueryService API (with tag QueryService) defines the API for procedure_call, Ahodc query.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: graphscope@alibaba-inc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.alibaba.graphscope.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Used for storage optimization
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BaseVertexTypeXCsrParams {
    public static final String SERIALIZED_NAME_MAX_VERTEX_NUM = "max_vertex_num";

    @SerializedName(SERIALIZED_NAME_MAX_VERTEX_NUM)
    private Integer maxVertexNum;

    public BaseVertexTypeXCsrParams() {}

    public BaseVertexTypeXCsrParams maxVertexNum(Integer maxVertexNum) {
        this.maxVertexNum = maxVertexNum;
        return this;
    }

    /**
     * Get maxVertexNum
     * @return maxVertexNum
     **/
    @javax.annotation.Nullable
    public Integer getMaxVertexNum() {
        return maxVertexNum;
    }

    public void setMaxVertexNum(Integer maxVertexNum) {
        this.maxVertexNum = maxVertexNum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BaseVertexTypeXCsrParams baseVertexTypeXCsrParams = (BaseVertexTypeXCsrParams) o;
        return Objects.equals(this.maxVertexNum, baseVertexTypeXCsrParams.maxVertexNum);
    }

    @Override
    public int hashCode() {
        return Objects.hash(maxVertexNum);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BaseVertexTypeXCsrParams {\n");
        sb.append("    maxVertexNum: ").append(toIndentedString(maxVertexNum)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("max_vertex_num");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to BaseVertexTypeXCsrParams
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!BaseVertexTypeXCsrParams.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in BaseVertexTypeXCsrParams is not found"
                                        + " in the empty JSON string",
                                BaseVertexTypeXCsrParams.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!BaseVertexTypeXCsrParams.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `BaseVertexTypeXCsrParams` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!BaseVertexTypeXCsrParams.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'BaseVertexTypeXCsrParams' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<BaseVertexTypeXCsrParams> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(BaseVertexTypeXCsrParams.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<BaseVertexTypeXCsrParams>() {
                        @Override
                        public void write(JsonWriter out, BaseVertexTypeXCsrParams value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public BaseVertexTypeXCsrParams read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of BaseVertexTypeXCsrParams given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of BaseVertexTypeXCsrParams
     * @throws IOException if the JSON string is invalid with respect to BaseVertexTypeXCsrParams
     */
    public static BaseVertexTypeXCsrParams fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, BaseVertexTypeXCsrParams.class);
    }

    /**
     * Convert an instance of BaseVertexTypeXCsrParams to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
