/*
 * GraphScope Interactive API v0.0.3
 * This is the definition of GraphScope Interactive API, including   - AdminService API   - Vertex/Edge API   - QueryService   AdminService API (with tag AdminService) defines the API for GraphManagement, ProcedureManagement and Service Management.  Vertex/Edge API (with tag GraphService) defines the API for Vertex/Edge management, including creation/updating/delete/retrive.  QueryService API (with tag QueryService) defines the API for procedure_call, Ahodc query.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: graphscope@alibaba-inc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.alibaba.graphscope.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * BaseEdgeType
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BaseEdgeType {
    public static final String SERIALIZED_NAME_TYPE_NAME = "type_name";

    @SerializedName(SERIALIZED_NAME_TYPE_NAME)
    private String typeName;

    public static final String SERIALIZED_NAME_VERTEX_TYPE_PAIR_RELATIONS =
            "vertex_type_pair_relations";

    @SerializedName(SERIALIZED_NAME_VERTEX_TYPE_PAIR_RELATIONS)
    private List<BaseEdgeTypeVertexTypePairRelationsInner> vertexTypePairRelations;

    public BaseEdgeType() {}

    public BaseEdgeType typeName(String typeName) {
        this.typeName = typeName;
        return this;
    }

    /**
     * Get typeName
     * @return typeName
     **/
    @javax.annotation.Nullable
    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public BaseEdgeType vertexTypePairRelations(
            List<BaseEdgeTypeVertexTypePairRelationsInner> vertexTypePairRelations) {
        this.vertexTypePairRelations = vertexTypePairRelations;
        return this;
    }

    public BaseEdgeType addVertexTypePairRelationsItem(
            BaseEdgeTypeVertexTypePairRelationsInner vertexTypePairRelationsItem) {
        if (this.vertexTypePairRelations == null) {
            this.vertexTypePairRelations = new ArrayList<>();
        }
        this.vertexTypePairRelations.add(vertexTypePairRelationsItem);
        return this;
    }

    /**
     * Get vertexTypePairRelations
     * @return vertexTypePairRelations
     **/
    @javax.annotation.Nullable
    public List<BaseEdgeTypeVertexTypePairRelationsInner> getVertexTypePairRelations() {
        return vertexTypePairRelations;
    }

    public void setVertexTypePairRelations(
            List<BaseEdgeTypeVertexTypePairRelationsInner> vertexTypePairRelations) {
        this.vertexTypePairRelations = vertexTypePairRelations;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BaseEdgeType baseEdgeType = (BaseEdgeType) o;
        return Objects.equals(this.typeName, baseEdgeType.typeName)
                && Objects.equals(
                        this.vertexTypePairRelations, baseEdgeType.vertexTypePairRelations);
    }

    @Override
    public int hashCode() {
        return Objects.hash(typeName, vertexTypePairRelations);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BaseEdgeType {\n");
        sb.append("    typeName: ").append(toIndentedString(typeName)).append("\n");
        sb.append("    vertexTypePairRelations: ")
                .append(toIndentedString(vertexTypePairRelations))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("type_name");
        openapiFields.add("vertex_type_pair_relations");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to BaseEdgeType
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!BaseEdgeType.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in BaseEdgeType is not found in the empty"
                                        + " JSON string",
                                BaseEdgeType.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!BaseEdgeType.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `BaseEdgeType` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("type_name") != null && !jsonObj.get("type_name").isJsonNull())
                && !jsonObj.get("type_name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `type_name` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("type_name").toString()));
        }
        if (jsonObj.get("vertex_type_pair_relations") != null
                && !jsonObj.get("vertex_type_pair_relations").isJsonNull()) {
            JsonArray jsonArrayvertexTypePairRelations =
                    jsonObj.getAsJsonArray("vertex_type_pair_relations");
            if (jsonArrayvertexTypePairRelations != null) {
                // ensure the json data is an array
                if (!jsonObj.get("vertex_type_pair_relations").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `vertex_type_pair_relations` to be an array"
                                            + " in the JSON string but got `%s`",
                                    jsonObj.get("vertex_type_pair_relations").toString()));
                }

                // validate the optional field `vertex_type_pair_relations` (array)
                for (int i = 0; i < jsonArrayvertexTypePairRelations.size(); i++) {
                    BaseEdgeTypeVertexTypePairRelationsInner.validateJsonElement(
                            jsonArrayvertexTypePairRelations.get(i));
                }
                ;
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!BaseEdgeType.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'BaseEdgeType' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<BaseEdgeType> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(BaseEdgeType.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<BaseEdgeType>() {
                        @Override
                        public void write(JsonWriter out, BaseEdgeType value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public BaseEdgeType read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of BaseEdgeType given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of BaseEdgeType
     * @throws IOException if the JSON string is invalid with respect to BaseEdgeType
     */
    public static BaseEdgeType fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, BaseEdgeType.class);
    }

    /**
     * Convert an instance of BaseEdgeType to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
