/*
 * GraphScope Interactive API v0.0.3
 * This is the definition of GraphScope Interactive API, including   - AdminService API   - Vertex/Edge API   - QueryService   AdminService API (with tag AdminService) defines the API for GraphManagement, ProcedureManagement and Service Management.  Vertex/Edge API (with tag GraphService) defines the API for Vertex/Edge management, including creation/updating/delete/retrive.  QueryService API (with tag QueryService) defines the API for procedure_call, Ahodc query.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: graphscope@alibaba-inc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.alibaba.graphscope.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * CreateGraphRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateGraphRequest {
    public static final String SERIALIZED_NAME_NAME = "name";

    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";

    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    private String description;

    public static final String SERIALIZED_NAME_STORED_PROCEDURES = "stored_procedures";

    @SerializedName(SERIALIZED_NAME_STORED_PROCEDURES)
    private List<CreateProcedureRequest> storedProcedures;

    public static final String SERIALIZED_NAME_SCHEMA = "schema";

    @SerializedName(SERIALIZED_NAME_SCHEMA)
    private CreateGraphSchemaRequest schema;

    public CreateGraphRequest() {}

    public CreateGraphRequest name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     **/
    @javax.annotation.Nullable
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public CreateGraphRequest description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * @return description
     **/
    @javax.annotation.Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public CreateGraphRequest storedProcedures(List<CreateProcedureRequest> storedProcedures) {
        this.storedProcedures = storedProcedures;
        return this;
    }

    public CreateGraphRequest addStoredProceduresItem(CreateProcedureRequest storedProceduresItem) {
        if (this.storedProcedures == null) {
            this.storedProcedures = new ArrayList<>();
        }
        this.storedProcedures.add(storedProceduresItem);
        return this;
    }

    /**
     * Get storedProcedures
     * @return storedProcedures
     **/
    @javax.annotation.Nullable
    public List<CreateProcedureRequest> getStoredProcedures() {
        return storedProcedures;
    }

    public void setStoredProcedures(List<CreateProcedureRequest> storedProcedures) {
        this.storedProcedures = storedProcedures;
    }

    public CreateGraphRequest schema(CreateGraphSchemaRequest schema) {
        this.schema = schema;
        return this;
    }

    /**
     * Get schema
     * @return schema
     **/
    @javax.annotation.Nullable
    public CreateGraphSchemaRequest getSchema() {
        return schema;
    }

    public void setSchema(CreateGraphSchemaRequest schema) {
        this.schema = schema;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateGraphRequest createGraphRequest = (CreateGraphRequest) o;
        return Objects.equals(this.name, createGraphRequest.name)
                && Objects.equals(this.description, createGraphRequest.description)
                && Objects.equals(this.storedProcedures, createGraphRequest.storedProcedures)
                && Objects.equals(this.schema, createGraphRequest.schema);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, description, storedProcedures, schema);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateGraphRequest {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    storedProcedures: ").append(toIndentedString(storedProcedures)).append("\n");
        sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("name");
        openapiFields.add("description");
        openapiFields.add("stored_procedures");
        openapiFields.add("schema");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to CreateGraphRequest
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!CreateGraphRequest.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in CreateGraphRequest is not found in the"
                                        + " empty JSON string",
                                CreateGraphRequest.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!CreateGraphRequest.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `CreateGraphRequest` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull())
                && !jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `name` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("name").toString()));
        }
        if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull())
                && !jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `description` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("description").toString()));
        }
        if (jsonObj.get("stored_procedures") != null
                && !jsonObj.get("stored_procedures").isJsonNull()) {
            JsonArray jsonArraystoredProcedures = jsonObj.getAsJsonArray("stored_procedures");
            if (jsonArraystoredProcedures != null) {
                // ensure the json data is an array
                if (!jsonObj.get("stored_procedures").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `stored_procedures` to be an array in the"
                                            + " JSON string but got `%s`",
                                    jsonObj.get("stored_procedures").toString()));
                }

                // validate the optional field `stored_procedures` (array)
                for (int i = 0; i < jsonArraystoredProcedures.size(); i++) {
                    CreateProcedureRequest.validateJsonElement(jsonArraystoredProcedures.get(i));
                }
                ;
            }
        }
        // validate the optional field `schema`
        if (jsonObj.get("schema") != null && !jsonObj.get("schema").isJsonNull()) {
            CreateGraphSchemaRequest.validateJsonElement(jsonObj.get("schema"));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CreateGraphRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CreateGraphRequest' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CreateGraphRequest> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(CreateGraphRequest.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<CreateGraphRequest>() {
                        @Override
                        public void write(JsonWriter out, CreateGraphRequest value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public CreateGraphRequest read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of CreateGraphRequest given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CreateGraphRequest
     * @throws IOException if the JSON string is invalid with respect to CreateGraphRequest
     */
    public static CreateGraphRequest fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CreateGraphRequest.class);
    }

    /**
     * Convert an instance of CreateGraphRequest to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
