/*
 * GraphScope Interactive API v0.0.3
 * This is the definition of GraphScope Interactive API, including   - AdminService API   - Vertex/Edge API   - QueryService   AdminService API (with tag AdminService) defines the API for GraphManagement, ProcedureManagement and Service Management.  Vertex/Edge API (with tag GraphService) defines the API for Vertex/Edge management, including creation/updating/delete/retrive.  QueryService API (with tag QueryService) defines the API for procedure_call, Ahodc query. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: graphscope@alibaba-inc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alibaba.graphscope.JSON;

/**
 * ServiceStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-07T17:50:52.209432+08:00[Asia/Shanghai]")
public class ServiceStatus {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_GRAPH_NAME = "graph_name";
  @SerializedName(SERIALIZED_NAME_GRAPH_NAME)
  private String graphName;

  public static final String SERIALIZED_NAME_BOLT_PORT = "bolt_port";
  @SerializedName(SERIALIZED_NAME_BOLT_PORT)
  private Integer boltPort;

  public static final String SERIALIZED_NAME_HQPS_PORT = "hqps_port";
  @SerializedName(SERIALIZED_NAME_HQPS_PORT)
  private Integer hqpsPort;

  public ServiceStatus() {
  }

  public ServiceStatus status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  public ServiceStatus graphName(String graphName) {
    this.graphName = graphName;
    return this;
  }

   /**
   * Get graphName
   * @return graphName
  **/
  @javax.annotation.Nullable
  public String getGraphName() {
    return graphName;
  }

  public void setGraphName(String graphName) {
    this.graphName = graphName;
  }


  public ServiceStatus boltPort(Integer boltPort) {
    this.boltPort = boltPort;
    return this;
  }

   /**
   * Get boltPort
   * @return boltPort
  **/
  @javax.annotation.Nullable
  public Integer getBoltPort() {
    return boltPort;
  }

  public void setBoltPort(Integer boltPort) {
    this.boltPort = boltPort;
  }


  public ServiceStatus hqpsPort(Integer hqpsPort) {
    this.hqpsPort = hqpsPort;
    return this;
  }

   /**
   * Get hqpsPort
   * @return hqpsPort
  **/
  @javax.annotation.Nullable
  public Integer getHqpsPort() {
    return hqpsPort;
  }

  public void setHqpsPort(Integer hqpsPort) {
    this.hqpsPort = hqpsPort;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceStatus serviceStatus = (ServiceStatus) o;
    return Objects.equals(this.status, serviceStatus.status) &&
        Objects.equals(this.graphName, serviceStatus.graphName) &&
        Objects.equals(this.boltPort, serviceStatus.boltPort) &&
        Objects.equals(this.hqpsPort, serviceStatus.hqpsPort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, graphName, boltPort, hqpsPort);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceStatus {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    graphName: ").append(toIndentedString(graphName)).append("\n");
    sb.append("    boltPort: ").append(toIndentedString(boltPort)).append("\n");
    sb.append("    hqpsPort: ").append(toIndentedString(hqpsPort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("status");
    openapiFields.add("graph_name");
    openapiFields.add("bolt_port");
    openapiFields.add("hqps_port");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ServiceStatus
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceStatus is not found in the empty JSON string", ServiceStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("graph_name") != null && !jsonObj.get("graph_name").isJsonNull()) && !jsonObj.get("graph_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `graph_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("graph_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceStatus>() {
           @Override
           public void write(JsonWriter out, ServiceStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ServiceStatus given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ServiceStatus
  * @throws IOException if the JSON string is invalid with respect to ServiceStatus
  */
  public static ServiceStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceStatus.class);
  }

 /**
  * Convert an instance of ServiceStatus to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

