[package]
name = "graph_index"
version = "0.1.0"
edition = "2021"

[dependencies]
pegasus_common = { path = "../../engine/pegasus/common"}
dyn_type = { path = "../../common/dyn_type" }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
itertools = "0.9"
lazy_static = "1.3.0"
log = "0.4"
crossbeam-utils = "0.6"
rust-htslib = { version = "0.39.5", default-features = false, features = ["bzip2", "lzma"] }
csv = "1.1"
rayon = "1.5.1"
bmcsr = { path = "../bmcsr" }

[lib]
name = "graph_index"
path = "src/lib.rs"
