# Persistent Volume to store graph
apiVersion: v1
kind: PersistentVolume
metadata:
  name: graph-store0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/gsbot/yufan/Graphs/LDBC_Partition0
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: graph-store-pvc-gaia-ir-rpc-0
    namespace: default
---
# Persistent Volume to store graph
apiVersion: v1
kind: PersistentVolume
metadata:
  name: graph-store1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/gsbot/yufan/Graphs/LDBC_Partition1
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: graph-store-pvc-gaia-ir-rpc-1
    namespace: default
---
# GAIA-IR-Compiler Service
apiVersion: v1
kind: Service
metadata:
  name: gaia-ir-compiler-cs
  labels:
    app: gaia-ir-compiler
spec:
  type: NodePort
  ports:
    - port: 8182
      targetPort: 8182
      nodePort: 31812
      name: listen-query
  selector:
    app: gaia-ir-compiler
---
# GAIA-IR-Compiler ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gaia-ir-compiler-rs
  labels:
    app: gaia-ir-compiler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gaia-ir-compiler
  template:
    metadata:
      labels:
        app: gaia-ir-compiler
    spec:
      containers:
        - name: gaia-ir-compiler
          imagePullPolicy: Never
          image: "gaia-ir-compiler:latest"
          ports:
            - containerPort: 8182
              name: listen-query
          env:
            - name: WORKER_NUM
              value: "2"
            - name: TIMEOUT
              value: "240000"
            - name: BATCH_SIZE
              value: "1024"
            - name: OUTPUT_CAPACITY
              value: "16"
            - name: GRAPH_SCHEMA
              value: "../executor/ir/core/resource/ldbc_schema.json"
            - name: SERVERSSIZE
              value: "2"
            - name: DNS_NAME_PREFIX_STORE
              value: "gaia-ir-rpc-{}.gaia-ir-rpc-hs.default.svc.cluster.local"
            - name: GAIA_RPC_PORT
              value: "1234"
          command:
            - sh
            - -c
            - "cd /opt/GraphScope/interactive_engine/compiler && \
              ./set_properties.sh && make run graph.schema:=$GRAPH_SCHEMA"
---
# GAIA-IR-RPC Headless Service
apiVersion: v1
kind: Service
metadata:
  name: gaia-ir-rpc-hs
  labels:
    app: gaia-ir-rpc
spec:
  ports:
    - port: 1234
      name: rpc
    - port: 11234
      name: repartition
  clusterIP: None
  selector:
    app: gaia-ir-rpc
---
# GAIA-IR-RPC Stateful Set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gaia-ir-rpc
spec:
  serviceName: gaia-ir-rpc-hs
  replicas: 2
  selector:
    matchLabels:
      app: gaia-ir-rpc
  template:
    metadata:
      labels:
        app: gaia-ir-rpc
    spec:
      containers:
        - name: gaia-ir-rpc
          imagePullPolicy: Never
          image: "gaia-ir-rpc:latest"
          ports:
            - containerPort: 1234
              name: rpc
            - containerPort: 11234
              name: repartition
          env:
            - name: SERVERSSIZE
              value: "2"
            - name: DNS_NAME_PREFIX_STORE
              value: "gaia-ir-rpc-{}.gaia-ir-rpc-hs.default.svc.cluster.local"
            - name: GAIA_RPC_PORT
              value: "1234"
            - name: GAIA_ENGINE_PORT
              value: "11234"
          command:
            - sh
            - -c
            - "DATA_PATH=/opt/graphs/ \
              /opt/GraphScope/interactive_engine/executor/ir/target/release/start_rpc_server_k8s"
          volumeMounts:
            - name: graph-store-pvc
              mountPath: /opt/graphs
  volumeClaimTemplates:
    - metadata:
        name: graph-store-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: ""