gs.gie.dbms.graph:
  name: modern
  graph:
    snapshotId: xx
    schema:
      vertexTypes:
      - typeId: 0
        typeName: person
        properties:
        - propertyId: 0
          propertyName: id
          propertyType:
            enumType: DT_UNSIGNED_INT64
        - propertyId: 1
          propertyName: name
          propertyType:
            enumType: DT_STRING
        - propertyId: 2
          propertyName: age
          propertyType:
            enumType: DT_UNSIGNED_INT32
        primaryKeyIds:
        - 0
      - typeId: 1
        typeName: software
        properties:
        - propertyId: 0
          propertyName: id
          propertyType:
            enumType: DT_UNSIGNED_INT64
        - propertyId: 1
          propertyName: name
          propertyType:
            enumType: DT_STRING
        - propertyId: 2
          propertyName: lang
          propertyType:
            enumType: DT_STRING
        - propertyId: 3
          propertyName: creationDateTime
          propertyType:
            dateTime:
              dateTimeFormat: DTF_YYYY_MM_DD_HH_MM_SS_SSS
              timeZoneFormat: TZF_UTC
        primaryKeyIds:
        - 0
      edgeTypes:
      - typeId: 0
        typeName: knows
        properties:
        - propertyId: 0
          propertyName: weight
          propertyType:
            enumType: DT_DOUBLE
        vertexTypePairRelations:
        - srcTypeId: 0
          dstTypeId: 0
          relation: MANY_TO_MANY
      - typeId: 1
        typeName: created
        properties:
        - propertyId: 0
          propertyName: weight
          propertyType:
            enumType: DT_DOUBLE
        vertexTypePairRelations:
        - srcTypeId: 0
          dstTypeId: 1
          relation: MANY_TO_MANY
