{{- $frontendFullname := include "graphscope-interactive.frontend.fullname" . }}
{{- $primaryFullName := include "graphscope-interactive.primary.fullname" . }}
{{- $secondaryFullName := include "graphscope-interactive.secondary.fullname" . }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $clusterDomain := .Values.clusterDomain }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "graphscope-interactive.primary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "graphscope-interactive.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
    {{- if .Values.commonLabels }}
    {{- include "graphscope-interactive.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "graphscope-interactive.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.primary.replicaCount }}
  selector:
    matchLabels: {{ include "graphscope-interactive.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: primary
  serviceName: {{ include "graphscope-interactive.primary.fullname" . }}
  updateStrategy:
    type: {{ .Values.primary.updateStrategy }}
    {{- if (eq "Recreate" .Values.primary.updateStrategy) }}
    rollingUpdate: null
    {{- end }}
  template:
    metadata:
      annotations:
        {{- if .Values.primary.podAnnotations }}
        {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.primary.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "graphscope-interactive.labels" . | nindent 8 }}
        app.kubernetes.io/component: primary
        {{- if .Values.primary.podLabels }}
        {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.primary.podLabels "context" $) | nindent 8 }}
        {{- end }}
        # alibabacloud.com/custom-cni-plugin-type: "nimitz"
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.primary.hostAliases }}
      hostAliases: {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.primary.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.primary.hostNetwork }}
      hostIPC: {{ .Values.primary.hostIPC }}
      {{- if .Values.primary.schedulerName }}
      schedulerName: {{ .Values.primary.schedulerName | quote }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig: {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.dnsConfig "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "graphscope-interactive.serviceAccountName" . }}
      {{- if .Values.primary.affinity }}
      affinity: {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.primary.affinity "context" $) | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.primary.initContainers }}
        {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.primary.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: proxy-admin
          image: {{ include "graphscope-interactive.primary.image" . }}
          imagePullPolicy: {{ .Values.primary.image.pullPolicy | quote }}
          # command: ["sleep", "infinity"]
          command:
            - /bin/bash
            - -c
            - |
              POD_NAME=$MY_POD_NAME
              if [ -z "$POD_NAME" ]; then
                POD_NAME=$(hostname)
              fi
              echo "POD_NAME: $POD_NAME"
              secondary_pod_dns_names=""
              # cnt=1
              # for i from 0 to $SECONDARY_REPLICAS
              for ((i=0; i<SECONDARY_REPLICAS; i++)); do
                secondary_pod_dns_names="$secondary_pod_dns_names,${SECONDARY_POD_NAME_PREFIX}-$i.${SECONDARY_SERVICE_NAME}:${SECONDARY_ADMIN_PORT}"
              #   cnt=$((cnt+1))
              done
              # secondary_pod_dns_names="${SECONDARY_SERVICE_NAME}:${SECONDARY_ADMIN_PORT}"
              # if secondary_pod_dns_names size > 0, remove the first comma
              if [ ${#secondary_pod_dns_names} -gt 0 ]; then
                secondary_pod_dns_names=${secondary_pod_dns_names:1}
              fi
              echo "secondary_pod_dns_names: $secondary_pod_dns_names"
              echo "cnt: $cnt"
              sudo chown -R graphscope:graphscope $INTERACTIVE_WORKSPACE
              cmd="/opt/flex/bin/entrypoint.sh -t proxy -e $secondary_pod_dns_names -p $PRIMARY_ADMIN_PORT --hang-until-success ${HANG_UNTIL_SUCCESS}"
              echo "cmd: $cmd"
              eval $cmd
              # sleep infinity
          env:
            - name: INSTANCE_NAME
              value: {{ .Release.Name | quote }}
            - name: INTERACTIVE_WORKSPACE
              value: {{ .Values.workspace | quote }}
            - name: PRIMARY_SERVICE_HOST
              value: {{ $primaryFullName }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }}
            - name: SECONDARY_POD_NAME_PREFIX
              value: {{ $secondaryFullName }}
            - name: SECONDARY_SERVICE_NAME
              value: {{ $secondaryFullName }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }}
            - name: SECONDARY_REPLICAS
              value: {{ .Values.secondary.replicaCount | quote }}
            - name: SECONDARY_QUERY_PORT
              value: {{ .Values.secondary.service.queryPort | quote }}
            - name: SECONDARY_ADMIN_PORT
              value: {{ .Values.secondary.service.adminPort | quote }}
            - name: PRIMARY_QUERY_PORT
              value: {{ .Values.primary.service.queryPort | quote }}
            - name: PRIMARY_ADMIN_PORT
              value: {{ .Values.primary.service.adminPort | quote }}
            - name: ENGINE_CONFIG_PATH
              value: {{ include "graphscope-interactive.engineConfigPath" . }}
            - name: REAL_ENGINE_CONFIG_PATH
              value: {{ include "graphscope-interactive.realEngineConfigPath" . }}
            - name: ENGINE_BINARY_PATH
              value: {{ include "graphscope-interactive.engineBinaryPath" . }}
            - name: ENGINE_SHARD_NUM
              value: {{ .Values.primary.threadNumPerWorker | quote }}
            - name: BULK_LOADER_BINARY_PATH
              value: /opt/flex/bin/bulk_loader
            - name: DEFAULT_GRAPH_NAME
              value: {{ .Values.defaultGraph }}
            - name: HANG_UNTIL_SUCCESS
              value: {{ .Values.primary.hangUntilSuccess | quote }}
            - name: ODPS_ACCESS_ID
              value: {{ .Values.odps.access.id | quote }}
            - name: ODPS_ACCESS_KEY
              value: {{ .Values.odps.access.key | quote }}
            - name: ODPS_ENDPOINT
              value: {{ .Values.odps.endpoint | quote }}
          ports:
            - name: admin-port
              containerPort: {{ .Values.primary.service.adminPort }}
          {{- if .Values.primary.resources }}
          resources: {{- toYaml .Values.primary.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: workspace
              mountPath: {{ .Values.workspace }}
            - name: config
              mountPath: {{ include "graphscope-interactive.engineConfigPath" . }}
              subPath: engine_config.yaml
        - name: nginx
          image: {{ include "graphscope-interactive.nginx.image" . }} 
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy | quote }}
          # command: ["sleep", "infinity"]
          ports:
            - name: query-port
              containerPort: {{ .Values.primary.service.queryPort }}
            - name: admin-port 
              containerPort: {{ .Values.primary.service.adminPort }}
          {{- if .Values.primary.resources }}
          resources: {{- toYaml .Values.primary.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: workspace
              mountPath: {{ .Values.workspace }}
            - name: config
              mountPath: {{ include "graphscope-interactive.engineConfigPath" . }}
              subPath: engine_config.yaml
            - name: nginx-config  
              mountPath: /etc/nginx/nginx.conf  
              subPath: nginx.conf
      volumes:
        - name: nginx-config  
          configMap:  
            name: {{ .Release.Name }}-nginx-config 
        - name: config
          configMap:
            name: {{ include "graphscope-interactive.configmapName" . }}
            defaultMode: 0755
  {{- if and .Values.primary.persistence.enabled .Values.primary.persistence.existingClaim }}
        - name: workspace
          persistentVolumeClaim:
            claimName: {{ tpl .Values.primary.persistence.existingClaim . }}
  {{- else if not .Values.primary.persistence.enabled }}
        - name: workspace
          emptyDir: {}
  {{- else if and .Values.primary.persistence.enabled (not .Values.primary.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: workspace
        {{- if .Values.persistence.annotations }}
        annotations: {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.persistence.annotations "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.persistence.labels }}
        labels: {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.persistence.labels "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.primary.persistence.size | quote }}
        {{ include "graphscope-interactive.storageClass" . | nindent 8 }}
        {{- if .Values.primary.persistence.selector }}
        selector: {{- include "graphscope-interactive.tplvalues.render" (dict "value" .Values.primary.persistence.selector "context" $) | nindent 10 }}
        {{- end -}}
  {{- end }}
