[package]
name = "pegasus_common"
version = "0.1.0"
authors = ["chenqiang.mcq <chenqiang.mcq@alibaba-inc.com>"]
edition = "2018"

[dependencies]
log = "0.4"
crossbeam-channel = "0.5.6"
crossbeam-queue = "0.3"
crossbeam-deque = "0.8"
crossbeam-utils = "0.8.14"
backtrace = "0.3.67"
log4rs = { version = "1.2", optional = true }
bitflags = "1.2.1"
bytes = "1.3"
byteorder = "1.4.3"
serde = { version = "1.0", optional = true }
env_logger = { version = "0.10" , optional = true }
smallvec = "1.6"
rand = "0.8.5"
time = { version = "0.3", optional = true, features = [ "formatting" ]}

[dev-dependencies]
bincode = "1.0.1"
rand = "0.8.5"

[features]
env_log = ["env_logger", "time"]
default = ["env_log"]