[package]
name = "ir_core"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
dyn_type = {path = "../../common/dyn_type"}
env_logger = "0.10"
ir_common = {path = "../common"}
lazy_static = "1.3.0"
log = "0.4"
pegasus_client = {path = "../../engine/pegasus/clients/rust/client"}
pegasus_server = {path = "../../engine/pegasus/server"}
pegasus = {path = "../../engine/pegasus/pegasus"}
prost = "0.11"
serde = "1.0"
serde_json = "1.0"
vec_map = { version = "0.8.2", features = ["serde"] }
rand = "0.8.5"
bimap = "0.6.2"

[features]
default = []
proto_inplace = ["ir_common/proto_inplace"]

