[package]
name = "build-probe-mpi"
version = "0.1.1"
authors = [
    "Benedikt Steinbusch <ben@rockshrub.de>",
    "Andrew Gaspar <andrew.gaspar@outlook.com>"
]
description = "Probes the system for an installation of an MPI library"
homepage = "https://github.com/bsteinb/rsmpi"
repository = "https://github.com/bsteinb/rsmpi"
categories = [ "development-tools::build-utils" ]
license = "MIT/Apache-2.0"

[dependencies]

[target.'cfg(unix)'.dependencies]
pkg-config = "0.3"
