[package]
name = "pegasus_graph"
version = "0.1.0"
authors = ["chenqiang.mcq <chenqiang.mcq@alibaba-inc.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.0"
nohash-hasher = "0.2.0"
#snap = "1"
rand = "0.8.3"
memmap = "0.7.0"

[dev-dependencies]
structopt = "0.2"