apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-simple
  namespace: default
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: registry.cn-hongkong.aliyuncs.com/graphscope/graphlearn-torch-client:0.26.0a20240115-x86_64
              imagePullPolicy: IfNotPresent
              command:
                - bash
                - -c
                - |- 
                  python3 -c "import time;time.sleep(1800)"
              volumeMounts:
              - mountPath: /dev/shm
                name: cache-volume
          volumes:
            - name: cache-volume
              emptyDir:
                medium: Memory
                sizeLimit: "8G"
    Worker:
      replicas: ${NUM_WORKER_REPLICAS}
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: registry.cn-hongkong.aliyuncs.com/graphscope/graphlearn-torch-client:0.26.0a20240115-x86_64
              imagePullPolicy: IfNotPresent
              command:
                - bash
                - -c
                - |-
                  python3 -c "import time;time.sleep(1800)"
              env:
                - name: GROUP_MASTER
                  value: pytorch-simple-master-0
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              volumeMounts:
              - mountPath: /dev/shm
                name: cache-volume
          volumes:
            - name: cache-volume
              emptyDir:
                medium: Memory
                sizeLimit: "8G"