apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: graphlearn-torch-client
  namespace: default
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: registry.cn-hongkong.aliyuncs.com/graphscope/graphlearn-torch:0.28.0a20240526
              imagePullPolicy: IfNotPresent
              command:
                - bash
                - -c
                - |- 
                  python3 /workspace/client.py --node_rank 0 --master_addr ${MASTER_ADDR} --num_server_nodes ${NUM_SERVER_NODES} --num_client_nodes ${NUM_CLIENT_NODES}
              volumeMounts:
              - mountPath: /dev/shm
                name: cache-volume
              - mountPath: /workspace
                name: client-volume
          volumes:
            - name: cache-volume
              emptyDir:
                medium: Memory
                sizeLimit: "8G"
            - name: client-volume
              configMap:
                name: graphlearn-torch-client-config
    Worker:
      replicas: ${NUM_WORKER_REPLICAS}
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: registry.cn-hongkong.aliyuncs.com/graphscope/graphlearn-torch:0.28.0a20240526
              imagePullPolicy: IfNotPresent
              command:
                - bash
                - -c
                - |-
                  python3 /workspace/client.py --node_rank $((${MY_POD_NAME: -1}+1)) --master_addr ${MASTER_ADDR} --group_master ${GROUP_MASTER} --num_server_nodes ${NUM_SERVER_NODES} --num_client_nodes ${NUM_CLIENT_NODES}
              env:
                - name: GROUP_MASTER
                  value: graphlearn-torch-client-master-0
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              volumeMounts:
              - mountPath: /dev/shm
                name: cache-volume
              - mountPath: /workspace
                name: client-volume
          volumes:
            - name: cache-volume
              emptyDir:
                medium: Memory
                sizeLimit: "8G"
            - name: client-volume
              configMap:
                name: graphlearn-torch-client-config
