[package]
name = "gremlin_core"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
lazy_static = "1.3.0"
enum_dispatch = "0.3"
bitflags = "1.2.1"
strum = "0.18.0"
strum_macros = "0.18.0"
crossbeam-queue = "0.1"
dyn-clonable = "0.9.0"
serde_json = "1.0"
pegasus = { path = "../../pegasus/pegasus" }
pegasus_server = { path = "../../pegasus/server" }
pegasus_common = { path = "../../pegasus/common" }
pegasus_config = { path = "../../pegasus/config" }
graph_store = { path = "../../graph_store" }
tonic = "0.3"
prost = "0.6"
tokio = { version = "0.2", features = ["macros", "sync"] }

[build-dependencies]
tonic-build = "0.3"

[features]
default = []
proto_inplace = []
