# coding: utf-8

"""
    GraphScope Interactive API v0.0.3

    This is the definition of GraphScope Interactive API, including   - AdminService API   - Vertex/Edge API   - QueryService   AdminService API (with tag AdminService) defines the API for GraphManagement, ProcedureManagement and Service Management.  Vertex/Edge API (with tag GraphService) defines the API for Vertex/Edge management, including creation/updating/delete/retrive.  QueryService API (with tag QueryService) defines the API for procedure_call, Ahodc query. 

    The version of the OpenAPI document: 1.0.0
    Contact: graphscope@alibaba-inc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from interactive_sdk.models.vertex_mapping import VertexMapping

class TestVertexMapping(unittest.TestCase):
    """VertexMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VertexMapping:
        """Test VertexMapping
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VertexMapping`
        """
        model = VertexMapping()
        if include_optional:
            return VertexMapping(
                type_name = '',
                inputs = [
                    ''
                    ],
                column_mappings = [
                    interactive_sdk.models.column_mapping.ColumnMapping(
                        column = interactive_sdk.models.edge_mapping_source_vertex_mappings_inner_column.EdgeMapping_source_vertex_mappings_inner_column(
                            index = 56, 
                            name = '', ), 
                        property = '', )
                    ]
            )
        else:
            return VertexMapping(
        )
        """

    def testVertexMapping(self):
        """Test VertexMapping"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
