FROM rust:1.55.0
WORKDIR /usr/src/pegasus/
COPY . .
RUN cp ./crates-io.config /usr/local/cargo/config
RUN rm -f Cargo.lock && cd ./khop && rm -f Cargo.lock
RUN cd ./khop && cargo install --path .
CMD ["pegasus-khop"]