{{- $frontendFullname := include "graphscope-store.frontend.fullname" . }}
{{- $storeFullname := include "graphscope-store.store.fullname" . }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $clusterDomain := .Values.clusterDomain }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "graphscope-store.store.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "graphscope-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: store
    {{- if .Values.commonLabels }}
    {{- include "graphscope-store.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "graphscope-store.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.store.replicaCount }}
  selector:
    matchLabels: {{ include "graphscope-store.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: store
  serviceName: {{ include "graphscope-store.store.fullname" . }}-headless
  updateStrategy:
    type: {{ .Values.store.updateStrategy }}
    {{- if (eq "Recreate" .Values.store.updateStrategy) }}
    rollingUpdate: null
    {{- end }}
  template:
    metadata:
      annotations:
        {{- if .Values.store.podAnnotations }}
        {{- include "graphscope-store.tplvalues.render" (dict "value" .Values.store.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "graphscope-store.labels" . | nindent 8 }}
        app.kubernetes.io/component: store
        {{- if .Values.commonLabels }}
        {{- include "graphscope-store.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "graphscope-store.serviceAccountName" . }}
      {{- if .Values.store.affinity }}
      affinity: {{- include "graphscope-store.tplvalues.render" (dict "value" .Values.store.affinity "context" $) | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.store.initContainers }}
        {{- include "graphscope-store.tplvalues.render" (dict "value" .Values.store.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: engine
          image: {{ include "graphscope-store.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
          {{- if (eq "Vineyard" .Values.storageType) }}
            - /bin/bash
            - -c
            - |
              sleep 5s

              chmod +x $GRAPHSCOPE_HOME/bin/kube_ssh
              sudo cp $GRAPHSCOPE_HOME/bin/kube_ssh /usr/bin/kube_ssh

              hosts=/tmp/hosts_of_nodes
              rm -rf $hosts && touch $hosts
              pod_ips=`kubectl get pod -lapp.kubernetes.io/component=store -o jsonpath='{.items[*].status.podIP}'`
              pod_names=""
              for ip in `echo $pod_ips`
              do
                pod_name=`kubectl get pods -o custom-columns=:metadata.name --no-headers=true --field-selector status.podIP=$ip`
                echo $ip $pod_name >> $hosts
                pod_names="${pod_names},${pod_name}"
              done
              pod_names=${pod_names:1}

              # start vineyard service
              export VINEYARD_IPC_SOCKET=/tmp/vineyard.sock
              if [ $SERVERSSIZE -eq 1 ]
              then
                $GRAPHSCOPE_HOME/../vineyard/vineyardd --socket=${VINEYARD_IPC_SOCKET} --meta=local &
              else
                $GRAPHSCOPE_HOME/../vineyard/vineyardd --socket=${VINEYARD_IPC_SOCKET} --etcd_endpoint=$ETCD_ENDPOINT &
              fi

              # load vineyard graph
              export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(python3 -c "import os; import vineyard; print(os.path.dirname(vineyard.__file__))")
              export OPAL_PREFIX=$(python3 -c "import os; import graphscope; print(os.path.abspath(os.path.dirname(graphscope.__file__) + '/../graphscope.runtime/openmpi'))")

              config_path=/etc/groot/config

              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              server_id=${BASH_REMATCH[1]}

              if [ $server_id -eq 0 ]
              then
                mpirun --host $pod_names \
                  -x LD_LIBRARY_PATH=$LD_LIBRARY_PATH \
                  -x OPAL_PREFIX=$OPAL_PREFIX \
                  -x VINEYARD_IPC_SOCKET=$VINEYARD_IPC_SOCKET \
                  -x config_path=$config_path \
                    $GRAPHSCOPE_HOME/bin/vineyard_htap_loader --config $config_path/$HTAP_LOADER_CONFIG
                if [ $? -ne 0 ]
                then
                  echo "load vineyard graph fail"
                  exit 1
                fi
              fi

              json_file=`ls /tmp/*.json`
              while [ $? -ne 0 ]
              do
                sleep 1s
                json_file=`ls /tmp/*.json`
              done
              object_id=${json_file//[^0-9]/}

              # start engine service
              pegasus_hosts=""
              i=0
              while [ $i -ne $SERVERSSIZE ]
              do
              pod=`echo $DNS_NAME_PREFIX_STORE | sed -e "s/{}/$i/g"`
              pegasus_hosts="${pegasus_hosts},${pod}:${GAIA_ENGINE_PORT}"
                i=$(($i+1))
              done
              pegasus_hosts=${pegasus_hosts:1}

              GRAPHSCOPE_RUNTIME=/tmp/gs/${object_id}
              GRAPHSCOPE_HOME=${GRAPHSCOPE_HOME} ${GRAPHSCOPE_HOME}/bin/giectl start_executor ${GRAPHSCOPE_RUNTIME} \
                ${object_id} ${server_id} ${SERVERSSIZE} ${GAIA_RPC_PORT} ${pegasus_hosts}

              exit_code=$?
              while [ $exit_code -eq 0 ]
              do
                sleep 10
              done
          {{- end }}
          {{- if (eq "Experimental" .Values.storageType) }}
            - /bin/bash
            - -c
            - |
              RUST_LOG=info DATA_PATH=${STORE_DATA_PATH} /opt/GraphScope/interactive_engine/executor/ir/target/release/start_rpc_server_k8s
          {{- end }}
          env:
            - name: GAIA_RPC_PORT
              value: {{ .Values.store.service.gaiaRpc | quote }}
            - name: GAIA_ENGINE_PORT
              value: {{ .Values.store.service.gaiaEngine | quote }}
            - name: STORE_DATA_PATH
              value: {{ .Values.storeDataPath | quote }}
            - name: DNS_NAME_PREFIX_STORE
              value: {{ $storeFullname }}-{}.{{ $storeFullname }}-headless.{{ $releaseNamespace }}.svc.{{ $clusterDomain }}
            - name: SERVERSSIZE
              value: {{ .Values.store.replicaCount | quote }}
            {{- if (eq "Vineyard" .Values.storageType) }}
            - name: ETCD_ENDPOINT
              value: {{ .Values.etcdEndpoint | quote }}
            - name: HTAP_LOADER_CONFIG
              value: {{ .Values.htapLoaderConfig | quote }}
            {{- end }}
          ports:
            - name: gaia-rpc
              containerPort: {{ .Values.store.service.gaiaRpc }}
            - name: gaia-engine
              containerPort: {{ .Values.store.service.gaiaEngine }}
          {{- if .Values.store.resources }}
          resources: {{- toYaml .Values.store.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.storeDataPath }}
            - name: config
              mountPath: /etc/groot/config
      volumes:
        - name: config
          configMap:
            name: {{ include "graphscope-store.configmapName" . }}
  {{- if and .Values.store.persistence.enabled .Values.store.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.store.persistence.existingClaim . }}
  {{- else if not .Values.store.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else if and .Values.store.persistence.enabled (not .Values.store.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: {{ include "graphscope-store.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: store
      {{- if .Values.store.persistence.annotations }}
        annotations:
          {{- toYaml .Values.store.persistence.annotations | nindent 10 }}
      {{- end }}
      spec:
        accessModes:
          {{- range .Values.store.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.store.persistence.size | quote }}
        {{ include "graphscope-store.storage.class" .Values.store.persistence }}
        {{- if .Values.store.persistence.selector }}
        selector: {{- include "graphscope-store.tplvalues.render" (dict "value" .Values.store.persistence.selector "context" $) | nindent 10 }}
        {{- end -}}
  {{- end }}
