/*
 * GraphScope Interactive API v0.0.3
 * This is the definition of GraphScope Interactive API, including   - AdminService API   - Vertex/Edge API   - QueryService   AdminService API (with tag AdminService) defines the API for GraphManagement, ProcedureManagement and Service Management.  Vertex/Edge API (with tag GraphService) defines the API for Vertex/Edge management, including creation/updating/delete/retrive.  QueryService API (with tag QueryService) defines the API for procedure_call, Ahodc query. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: graphscope@alibaba-inc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.graphscope.interactive;

import com.alibaba.graphscope.ApiException;
import org.openapitools.client.model.Service;
import org.openapitools.client.model.ServiceStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminServiceServiceManagementApi
 */
@Disabled
public class AdminServiceServiceManagementApiTest {

    private final AdminServiceServiceManagementApi api = new AdminServiceServiceManagementApi();

    /**
     * Get service status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceStatusTest() throws ApiException {
        ServiceStatus response = api.getServiceStatus();
        // TODO: test validations
    }

    /**
     * Start current service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void restartServiceTest() throws ApiException {
        String response = api.restartService();
        // TODO: test validations
    }

    /**
     * Start service on a specified graph
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void startServiceTest() throws ApiException {
        Service service = null;
        String response = api.startService(service);
        // TODO: test validations
    }

    /**
     * Stop current service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void stopServiceTest() throws ApiException {
        String response = api.stopService();
        // TODO: test validations
    }

}
