/*
 * GraphScope Interactive API v0.0.3
 * This is the definition of GraphScope Interactive API, including   - AdminService API   - Vertex/Edge API   - QueryService   AdminService API (with tag AdminService) defines the API for GraphManagement, ProcedureManagement and Service Management.  Vertex/Edge API (with tag GraphService) defines the API for Vertex/Edge management, including creation/updating/delete/retrive.  QueryService API (with tag QueryService) defines the API for procedure_call, Ahodc query. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: graphscope@alibaba-inc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.graphscope.interactive;

import com.alibaba.graphscope.ApiException;
import org.openapitools.client.model.JobStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminServiceJobManagementApi
 */
@Disabled
public class AdminServiceJobManagementApiTest {

    private final AdminServiceJobManagementApi api = new AdminServiceJobManagementApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteJobByIdTest() throws ApiException {
        String jobId = null;
        String response = api.deleteJobById(jobId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getJobByIdTest() throws ApiException {
        String jobId = null;
        JobStatus response = api.getJobById(jobId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listJobsTest() throws ApiException {
        List<JobStatus> response = api.listJobs();
        // TODO: test validations
    }

}
