apiVersion: v1
kind: Pod
metadata:
  name: unique_pod_name
  labels:
    graph: unique_pod_name
spec:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: kubernetes.io/hostname
  #           operator: In
  #           values:
  #           - k8s_node_host
  containers:
  - image: gremlin_image
    resources:
      requests:
        cpu: requests_cpu
        memory: requests_mem
      limits:
        cpu: limits_cpu
        memory: limits_mem
    name: gremlin-container
    imagePullPolicy: IfNotPresent
    args:
      - "/home/maxgraph/bin/giectl"
      - "start_frontend"
      - "k8s"
      - "unique_object_id"
      - "unique_schema_path"
      - "zookeeper_ip"
      - "2181"
      - "unique_executor_count"
      - "False"
    env:
    - name: OBJECT_ID
      value: 'unique_object_id'
    volumeMounts:
    - mountPath: /home/maxgraph/schema
      name: config-volume
  - image: coordinator_image
    resources:
      requests:
        cpu: requests_cpu
        memory: requests_mem
      limits:
        cpu: limits_cpu
        memory: limits_mem
    name: coordinator-container
    imagePullPolicy: IfNotPresent
    args:
      - "/home/maxgraph/bin/giectl"
      - "start_coordinator"
      - "k8s"
      - "unique_object_id"
      - "zookeeper_ip"
      - "2181"
      - "unique_executor_count"
      - "False"
    env:
    - name: OBJECT_ID
      value: 'unique_object_id'
    volumeMounts:
    - mountPath: /home/maxgraph/schema
      name: config-volume
  volumes:
  - name: config-volume
    configMap:
      name: unique_schema_name
