[build-system]
requires = ["setuptools_scm", "grpcio>=1.49", "grpcio-tools>=1.49", "mypy-protobuf", "numpy", "wheel"]

[tool.black]
line-length = 88
exclude = '''
(
  .*forward.*
  | .*node_modules.*
  | .*\.eggs.*
  | .*build/.*
  | ^/dist.*
  | .*_pb2\.py
  | .*_pb2_grpc\.py
)
'''

