[build-system]
requires = ["setuptools_scm", "grpcio<=1.43.0,>=1.40.0", "grpcio-tools<=1.43.0,>=1.40.0", "numpy", "wheel"]

[tool.black]
line-length = 88
exclude = '.*\/(forward|node_modules|\.eggs|build|_pb2\.py)\/.*'
