apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphscope-interactive.configmapName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "graphscope-interactive.labels" . | nindent 4 }}
    app.kubernetes.io/component: configmap
    {{- if .Values.commonLabels }}
    {{- include "graphscope-interactive.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "graphscope-interactive.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  interactive_config.yaml: |-
    log_level: {{ .Values.logLevel  }}
    default_graph: {{ .Values.defaultGraph }}
    compute_engine:
      type: hiactor
      workers:
        - localhost:10000
      thread_num_per_worker: {{ .Values.primary.threadNumPerWorker }}
    compiler:
      planner:
        is_on: true
        opt: RBO
        rules:
          - FilterIntoJoinRule
          - FilterMatchRule
          - NotMatchToAntiJoinRule
      endpoint:
        default_listen_address: localhost
        bolt_connector:
          disabled: false
          port: {{ .Values.frontend.service.cypherPort }}
        gremlin_connector:
          disabled: true
          port: {{ .Values.frontend.service.gremlinPort  }}
      query_timeout: {{ .Values.frontend.service.queryTimeout  }}
    http_service:
      default_listen_address: localhost
      admin_port: {{ .Values.primary.service.adminPort  }}
      query_port: {{ .Values.primary.service.queryPort  }}