apiVersion: v1
kind: PersistentVolume
metadata:
  name: graphscope-interactive-pv
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data
  claimRef:
    name: graphscope-interactive-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphscope-interactive-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce