version: '3' # version of docker-compose
services:
  engine:
    image: "hqps-server-runtime:latest"
    ports:
     - "10000:10000"
    container_name: hqps-server
#    command : ["./hiactor-server", "-c", "config.yaml"] # command to start hqps_server
    volumes : 
      - /home/zhanglei/gie-db:/root/db_config # mount db directory
  compiler:
    image: "hqps-compiler-runtime:latest"
    ports: 
    - "7687:7687"
    container_name: hqps-compiler
#    command : ["./hiactor-compiler", "-c", "config.yaml"] # command to start hqps_compiler
    depends_on:
      - engine 



# to start compiler
# we need to create a new ir.compiler.properties, can copy to /Graphscope/interactive_engine/conf/ir.compiler.properties
# set graph_schema
# hiactor.hosts
# graph.store.
# graph.planner
# gremlin.server.disabled: true


# to start server,
# graph.yaml
# thread num
# http_port
# data_path.