version: '3' # version of docker-compose
services:
  engine:
    tty: true
    image: "hqps-server-runtime:latest"
    network_mode: "host"
    container_name: hqps-server
#    command : ["./hiactor-server", "-c", "config.yaml"] # command to start hqps_server
    volumes : 
      - /home/zhanglei/code/GraphScope/flex/gie-db:/home/zhanglei/code/GraphScope/flex/gie-db
      - /home/zhanglei/gstest/:/home/zhanglei/gstest/
  compiler:
    tty: true
    image: "hqps-compiler-runtime:latest"
    network_mode: "host"
    container_name: hqps-compiler
#    command : ["./hiactor-compiler", "-c", "config.yaml"] # command to start hqps_compiler
    depends_on:
      - engine 
    volumes:
      - /home/zhanglei/code/GraphScope/flex/gie-db:/home/zhanglei/code/GraphScope/flex/gie-db



      # - 6362:6362
      # - 7474:7474
      # - 7687:7687
# to start compiler
# we need to create a new ir.compiler.properties, can copy to /Graphscope/interactive_engine/conf/ir.compiler.properties
# set graph_schema
# hiactor.hosts
# graph.store.
# graph.planner
# gremlin.server.disabled: true


# to start server,
# graph.yaml
# thread num
# http_port
# data_path.
