[package]
name = "gs_gremlin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
maxgraph-store = {path = "../../../../interactive_engine/executor/store"}
gremlin_core = {path="../gremlin_core"}
dyn_type = { path = "../../../dyn_type" }
structopt = "0.2"
tokio = { version = "1.0", features = ["macros", "sync"] }
pegasus = { path = "../../../engine/pegasus/pegasus" }
pegasus_server = { path = "../../../engine/pegasus/server-v0" }
pegasus_common = { path = "../../../engine/pegasus/common" }