from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_flex_coordinator.models.base_model import Model
from gs_flex_coordinator import util


class JobResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, job_id=None):  # noqa: E501
        """JobResponse - a model defined in OpenAPI

        :param job_id: The job_id of this JobResponse.  # noqa: E501
        :type job_id: str
        """
        self.openapi_types = {
            'job_id': str
        }

        self.attribute_map = {
            'job_id': 'job_id'
        }

        self._job_id = job_id

    @classmethod
    def from_dict(cls, dikt) -> 'JobResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobResponse of this JobResponse.  # noqa: E501
        :rtype: JobResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job_id(self) -> str:
        """Gets the job_id of this JobResponse.


        :return: The job_id of this JobResponse.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id: str):
        """Sets the job_id of this JobResponse.


        :param job_id: The job_id of this JobResponse.
        :type job_id: str
        """

        self._job_id = job_id
