[workspace]

[package]
name = "dynlib-exp"
version = "0.1.0"
edition = "2018"

[dependencies]
pegasus = { path = "../../../pegasus" }
pegasus_server = { path = "../../../server" }

[lib]
name = "dynexp"
crate-type = ["dylib"]