[workspace]
members = [
    "common",
    "config",
    "memory",
    "network",
    "executor",
    "pegasus",
    "server",
    "graph"
]

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false