name: Build GraphScope Manylinux Images

# build `graphscope/manylinux2014` image based on centos7, including all necessary
# dependencies except vineyard
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'python/graphscope/gsctl/scripts/**'
      - '.github/workflows/build-graphscope-manylinux-images.yml'


concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  REGISTRY: registry.cn-hongkong.aliyuncs.com

jobs:
  build-manylinux-image-amd64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Image
      run: |
        cd ${GITHUB_WORKSPACE}/k8s
        # output: graphscope/manylinux:amd64
        make manylinux2014

    - name: Release Image
      if: ${{ github.event_name == 'workflow_dispatch' }}
      env:
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        docker_username: ${{ secrets.DOCKER_USER }}
      run: |
        echo "${docker_password}" | sudo docker login --username="${docker_username}" ${{ env.REGISTRY }} --password-stdin
        # manylinux2014 image
        sudo docker tag graphscope/manylinux2014:amd64 ${{ env.REGISTRY }}/graphscope/manylinux2014:amd64
        sudo docker push ${{ env.REGISTRY }}/graphscope/manylinux2014:amd64
