name: Build GraphScope Wheel Images

# build `graphscope/graphscope-dev:wheel-{v6d_version}` image based on manylinux,
# including all dependencies for building graphscope wheel package.
on:
  workflow_dispatch:
    inputs:
      v6d_version:
        description: 'Version for Vineyard (v6d)'
        required: true
        default: 'main'
  pull_request:
    branches:
      - main
    paths:
      - 'python/graphscope/gsctl/scripts/**'
      - '.github/workflows/build-graphscope-dev-wheel-images.yml'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  REGISTRY: registry.cn-hongkong.aliyuncs.com

jobs:
  build-wheel-image-amd64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Image
      run: |
        # build wheel image with specified v6d's version
        cd ${GITHUB_WORKSPACE}/k8s
        VINEYARD_VERSION=${{ github.event.inputs.v6d_version }}
        if [[ -n ${VINEYARD_VERSION} ]]; then
          # graphscope/graphscope-dev:wheel-<v6d_version>-amd64
          make dev-wheel VINEYARD_VERSION=${VINEYARD_VERSION}
        else
          # pull_request: use default vineyard_version
          make dev-wheel
        fi

    - name: Release Image
      if: ${{ github.event_name == 'workflow_dispatch' }}
      env:
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        docker_username: ${{ secrets.DOCKER_USER }}
      run: |
        echo "${docker_password}" | sudo docker login --username="${docker_username}" ${{ env.REGISTRY }} --password-stdin
        VINEYARD_VERSION=${{ github.event.inputs.v6d_version }}
        sudo docker tag graphscope/graphscope-dev:wheel-${VINEYARD_VERSION}-amd64 ${{ env.REGISTRY }}/graphscope/graphscope-dev:wheel-${VINEYARD_VERSION}-amd64
        sudo docker push ${{ env.REGISTRY }}/graphscope/graphscope-dev:wheel-${VINEYARD_VERSION}-amd64
