name: Cancel Stale Runs

on: [push, pull_request_target]

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: local.yml,ci.yml,build-graphscope-wheels-linux.yml,build-graphscope-wheels-macos.yml,gaia.yml
          access_token: ${{ github.token }}

