name: GraphScope CI on Local

on:
  schedule:
    # Trigger the workflow at 03:00 every day
    - cron:  '00 03 * * *'

jobs:
  build-images:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2.3.2

    - name: Prepare Image
      run: |
        sudo docker build -t registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:${{ github.sha }} \
                          --network=host \
                          -f .k8s/graphscope.Dockerfile .
        sudo docker build -t registry.cn-hongkong.aliyuncs.com/graphscope/maxgraph_standalone_manager:${{ github.sha }} \
                          --network=host \
                          -f .k8s/manager.Dockerfile .
        sudo docker build -t registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-store:${{ github.sha }} \
                          --network=host \
                          -f .k8s/graphscope-store.Dockerfile .

    - name: Clean
      if: always()
      run: |
        sudo docker rmi -f registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:${{ github.sha }} || true
        sudo docker rmi -f registry.cn-hongkong.aliyuncs.com/graphscope/maxgraph_standalone_manager:${{ github.sha }} || true
        sudo docker rmi -f registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-store:${{ github.sha }} || true

