name: GraphScope Flex CI (Dummy)

on:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!flex/**'
      - '!.github/workflows/flex.yml'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-gae:
    runs-on: ubuntu-20.04
    if: ${{ github.repository == 'alibaba/GraphScope' }}
    steps:
    - run: 'echo "No action required" '