name: GraphScope CI  on Kubernetes (Dummy)

on:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!.github/workflows/ci.yml'
      - '!Makefile'
      - '!analytical_engine/**'
      - '!charts/**'
      - '!coordinator/**'
      - '!interactive_engine/**'
      - '!k8s/**'
      - '!learning_engine/**'
      - '!proto/**'
      - '!python/**'
      - '**.md'
      - '**.rst'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GS_IMAGE: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-20.04
    # Set job outputs to values from filter step
    outputs:
      gae-python: ${{ steps.filter.outputs.gae-python }}
      networkx: ${{ steps.filter.outputs.networkx }}
      gie-function-test: ${{ steps.filter.outputs.gie-function-test }}
    steps:
    # For push it's necessary to checkout the code
    - uses: actions/checkout@v3
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: main  # Change detection against merge-base with main before push
        filters: |
          gae-python:
            - 'proto/**'
            - 'analytical_engine/**'
            - 'python/graphscope/analytical/**'
            - 'python/graphscope/client/**'
            - 'python/graphscope/dataset/**'
            - 'python/graphscope/deploy/**'
            - 'python/graphscope/framework/**'
            - 'python/graphscope/tests/unittest/**'
            - 'coordinator/gscoordinator/**'
            - '.github/workflows/ci.yml'
          networkx:
            - 'analytical_engine/apps/**'
            - 'analytical_engine/frame/**'
            - 'analytical_engine/core/**'
            - 'python/graphscope/nx/**'
          gie-function-test:
            - 'interactive_engine/**'
            - 'python/graphscope/interactive/**'
            - '.github/workflows/ci.yml'

  build-analytical:
    runs-on: ubuntu-20.04
    needs: [build-wheels, changes]
    if: ${{ github.repository == 'alibaba/GraphScope' }}
    steps:
    - run: 'echo "No action required" '

  build-analytical-java:
    runs-on: ubuntu-20.04
    needs: [build-wheels, changes]
    if: ${{ github.repository == 'alibaba/GraphScope' }}
    steps:
    - run: 'echo "No action required" '

  build-interactive:
    runs-on: ubuntu-20.04
    needs: [build-wheels, changes]
    if: ${{ github.repository == 'alibaba/GraphScope' }}
    steps:
    - run: 'echo "No action required" '

  build-learning:
    runs-on: ubuntu-20.04
    needs: [build-wheels, changes]
    if: ${{ github.repository == 'alibaba/GraphScope' }}
    steps:
    - run: 'echo "No action required" '

  # build-coordinator:
  #   runs-on: ubuntu-20.04
  #   needs: [build-wheels, changes]
  #   if: ${{ github.repository == 'alibaba/GraphScope' }}
  #   steps:
  #   - run: 'echo "No action required" '

  k8s-test:
    runs-on: ubuntu-20.04
    if: ${{ github.repository == 'alibaba/GraphScope' }}
    needs: [build-analytical, build-analytical-java, build-interactive, build-learning]
    steps:
    - run: 'echo "No action required" '

  gie-test:
    runs-on: ubuntu-20.04
    needs: [build-analytical, build-analytical-java, build-interactive, build-learning]
    if: ${{ (needs.changes.outputs.gie-function-test == 'false' || github.ref == 'refs/heads/main') && github.repository == 'alibaba/GraphScope' }}
    steps:
    - run: 'echo "No action required" '
