name: GraphScope minimum CI on Local

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    paths-ignore:
      - 'gnn_engine/**'
      - '**.md'
      - '**.rst'
      - 'docs/**'
      - 'research/**'
      - 'scripts/**'
      - 'tutorials/**'
  pull_request:
    paths-ignore:
      - 'gnn_engine/**'
      - '**.md'
      - '**.rst'
      - 'docs/**'
      - 'research/**'
      - 'scripts/**'
      - 'tutorials/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies of GraphScope
      run: |
        /bin/bash ${GITHUB_WORKSPACE}/scripts/deploy_local.sh --verbose install_deps

        # avoid access node by DNS hostnames
        r=`cat /etc/hosts | grep $(hostname) || true`
        if [ -z "${r}" ];then export hn=$(hostname); sudo -E bash -c 'echo "127.0.0.1 ${hn}" >> /etc/hosts'; fi
        cat /etc/hosts

    - name: Build GraphScope
      run: |
        source ${GITHUB_WORKSPACE}/gs_env
        /bin/bash ${GITHUB_WORKSPACE}/scripts/deploy_local.sh --verbose deploy

    - name: Run Local Test
      env:
        OS : ${{ matrix.os }}
      run: |
        source ${GITHUB_WORKSPACE}/gs_env
        export GRAPHSCOPE_PREFIX=/usr/local
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib

        # install tensorflow for graphlearn if os is ubuntu20.04
        if [ "${OS}" == "ubuntu-20.04" ];
        then
            pip3 install pytest tensorflow --user;
        fi

        # prelaunch the etcd
        /usr/local/bin/etcd --data-dir=/tmp/default.etcd &

        export GS_TEST_DIR=${GITHUB_WORKSPACE}/gstest
        git clone -b master --single-branch --depth=1 https://github.com/7br/gstest.git ${GS_TEST_DIR}
        rm -rf ~/.ccache ~/.m2 ~/.cargo || true
        cd python
        python3 -m pytest -s -v tests/test_minimum.py

        # delete etcd dir
        rm -fr /tmp/default.etcd || true

    - name: Upload GIE Log
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: gie-log-minimum
        path: /tmp/graphscope/

    - name: Setup tmate session debug
      if: false
      uses: mxschmitt/action-tmate@v2
