[package]
name = "runtime_integration"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
crossbeam-channel = "0.4.4"
prost = "0.9"
lazy_static = "1.3.0"
structopt = "0.2"
tokio = { version = "1.0", features = ["macros", "sync"] }
clap = "2.32.0"
pegasus = { path = "../../engine/pegasus/pegasus" }
pegasus_client = {path = "../../engine/pegasus/clients/rust/client"}
pegasus_server = { path = "../../engine/pegasus/server" }
pegasus_common = { path = "../../engine/pegasus/common" }
ir_common = {path = "../common"}
ir_core = {path = "../core"}
runtime = {path="../runtime"}
graph_proxy = {path = "../graph_proxy"}
graph_store = {path = "../../store/exp_store"}
dyn_type = {path = "../../common/dyn_type"}
global_query = {path = "../../store/global_query"}

[features]
default = []
proto_inplace = ["ir_common/proto_inplace", "pegasus_server/gcip"]
with_v6d = ["runtime/with_v6d"]
column_filter_push_down = []