graph: dd_graph
loading_config:
  data_source:
    scheme: odps  # file, oss, s3, hdfs; only file is supported now
  import_option: init # append, overwrite, only init is supported now
  format:
    type: arrow
    metadata:
      batch_reader: true 
      batch_size: 16MB
vertex_mappings:
  - type_name: User  # must align with the schema
    inputs:
      - dd_undata/dim_ding_user_node/ds=20231231
    column_mappings:
      - column:
          index: 0    # can be omitted if the index is the same as the property index
          name: ding_user_id  # can be omitted if the name is not known
        property: id
      - column:
          index: 3
          name: role_name
        property: roleName
      - column:
          index: 4
          name: act_usr_days_1m
        property: activeDays
  - type_name: DingOrg
    inputs:
      - dd_undata/dim_ding_org_node/ds=20231231
    column_mappings:
      - column:
          index: 0
          name: org_id
        property: id
  - type_name: DingEduOrg
    inputs:
      - dd_undata/dim_ding_edu_org_node/ds=20231231
    column_mappings:
      - column:
          index: 0
          name: org_id
        property: id
edge_mappings:
  - type_triplet:
      edge: WorkAt
      source_vertex: User
      destination_vertex: DingOrg
    inputs:
      - dd_undata/dim_ding_org_user_edge/ds=20231231
    source_vertex_mappings:
      - column:
          index: 0
          name: ding_user_id
        property: id
    destination_vertex_mappings:
      - column:
          index: 1
          name: org_id
        property: id
    column_mappings:
      - column:
          index: 2
          name: gmt_create_mill
        property: joinDate
  - type_triplet:
      edge: StudyAt
      source_vertex: User
      destination_vertex: DingEduOrg
    inputs:
      - dd_undata/dim_ding_edu_org_user_edge/ds=20231231
    source_vertex_mappings:
      - column:
          index: 0
          name: ding_user_id
        property: id
    destination_vertex_mappings:
      - column:
          index: 1
          name: org_id
        property: id
    column_mappings:
      - column:
          index: 2
          name: gmt_create_mill
        property: joinDate
        # - column:
      #     index: 4
      #     name: profession
      #   property: profession




